 ; CHANGE
InitCustomStarter:
	push af
	push hl

	ld a, 129 ; Default alphabetical-ordered starter ID ; Squirtle
	ld [wCustomStarterAlphabeticalID], a
	call SetCustomStarterIDs
	ld a, $f
	ld hl, wCustomStarterAtkDV
	ld [hli], a ; Atk
	ld [hli], a ; Def
	ld [hli], a ; Spe
	ld [hl], a  ; Spc
	xor a
	set 1, a
	ld [wCustomStarterPosition], a
	ld a, STARTER1
	ld [wCustomStarter1], a
	ld a, [wCustomStarterInternalID]
	ld [wCustomStarter2], a
	ld a, STARTER3
	ld [wCustomStarter3], a
	ld a, 7
	ld [wCustomStarterPositionX], a

	pop hl
	pop af
	ret
	
SetCustomStarterIDs:
	ld a, [wCustomStarterAlphabeticalID]
	ld d, 0
	ld e, a
	ld hl, PokemonAlphabeticalList
	add hl, de
	add hl, de
	ld a, [hli] ; gets internal Pokémon ID
	ld [wCustomStarterInternalID], a
	ld a, [hl] ; gets Dex Pokémon ID
	ld [wCustomStarterDexID], a
	ret
	
PokemonAlphabeticalList::
	db ABRA, 		DEX_ABRA		;  0
	db AERODACTYL, 	DEX_AERODACTYL
	db ALAKAZAM, 	DEX_ALAKAZAM
	db ARBOK, 		DEX_ARBOK
	db ARCANINE, 	DEX_ARCANINE
	db ARTICUNO, 	DEX_ARTICUNO
	db BEEDRILL, 	DEX_BEEDRILL
	db BELLSPROUT, 	DEX_BELLSPROUT
	db BLASTOISE, 	DEX_BLASTOISE
	db BULBASAUR, 	DEX_BULBASAUR
	db BUTTERFREE, 	DEX_BUTTERFREE	; 10
	db CATERPIE, 	DEX_CATERPIE
	db CHANSEY, 	DEX_CHANSEY
	db CHARIZARD, 	DEX_CHARIZARD
	db CHARMANDER, 	DEX_CHARMANDER
	db CHARMELEON, 	DEX_CHARMELEON
	db CLEFABLE, 	DEX_CLEFABLE
	db CLEFAIRY, 	DEX_CLEFAIRY
	db CLOYSTER, 	DEX_CLOYSTER
	db CUBONE, 		DEX_CUBONE
	db DEWGONG, 	DEX_DEWGONG		; 20
	db DIGLETT,		DEX_DIGLETT
	db DITTO, 		DEX_DITTO
	db DODRIO, 		DEX_DODRIO
	db DODUO, 		DEX_DODUO
	db DRAGONAIR, 	DEX_DRAGONAIR
	db DRAGONITE, 	DEX_DRAGONITE
	db DRATINI, 	DEX_DRATINI
	db DROWZEE, 	DEX_DROWZEE
	db DUGTRIO, 	DEX_DUGTRIO
	db EEVEE, 		DEX_EEVEE		; 30
	db EKANS, 		DEX_EKANS
	db ELECTABUZZ, 	DEX_ELECTABUZZ
	db ELECTRODE, 	DEX_ELECTRODE
	db EXEGGCUTE, 	DEX_EXEGGCUTE
	db EXEGGUTOR, 	DEX_EXEGGUTOR
	db FARFETCHD, 	DEX_FARFETCHD
	db FEAROW, 		DEX_FEAROW
	db FLAREON, 	DEX_FLAREON
	db GASTLY, 		DEX_GASTLY
	db GENGAR, 		DEX_GENGAR		; 40
	db GEODUDE, 	DEX_GEODUDE
	db GLOOM, 		DEX_GLOOM
	db GOLBAT, 		DEX_GOLBAT
	db GOLDEEN, 	DEX_GOLDEEN
	db GOLDUCK, 	DEX_GOLDUCK
	db GOLEM, 		DEX_GOLEM
	db GRAVELER, 	DEX_GRAVELER
	db GRIMER, 		DEX_GRIMER
	db GROWLITHE, 	DEX_GROWLITHE
	db GYARADOS, 	DEX_GYARADOS	; 50
	db HAUNTER, 	DEX_HAUNTER
	db HITMONCHAN, 	DEX_HITMONCHAN
	db HITMONLEE, 	DEX_HITMONLEE
	db HORSEA, 		DEX_HORSEA
	db HYPNO, 		DEX_HYPNO
	db IVYSAUR, 	DEX_IVYSAUR
	db JIGGLYPUFF, 	DEX_JIGGLYPUFF
	db JOLTEON, 	DEX_JOLTEON
	db JYNX, 		DEX_JYNX
	db KABUTO, 		DEX_KABUTO		; 60
	db KABUTOPS, 	DEX_KABUTOPS
	db KADABRA, 	DEX_KADABRA
	db KAKUNA, 		DEX_KAKUNA
	db KANGASKHAN, 	DEX_KANGASKHAN
	db KINGLER, 	DEX_KINGLER
	db KOFFING, 	DEX_KOFFING
	db KRABBY, 		DEX_KRABBY
	db LAPRAS, 		DEX_LAPRAS
	db LICKITUNG, 	DEX_LICKITUNG
	db MACHAMP, 	DEX_MACHAMP		; 70
	db MACHOKE, 	DEX_MACHOKE
	db MACHOP, 		DEX_MACHOP
	db MAGIKARP,	DEX_MAGIKARP
	db MAGMAR, 		DEX_MAGMAR
	db MAGNEMITE, 	DEX_MAGNEMITE
	db MAGNETON, 	DEX_MAGNETON
	db MANKEY, 		DEX_MANKEY
	db MAROWAK, 	DEX_MAROWAK
	db MEOWTH, 		DEX_MEOWTH
	db METAPOD, 	DEX_METAPOD		; 80
	db MEW, 		DEX_MEW
	db MEWTWO, 		DEX_MEWTWO
	db MOLTRES, 	DEX_MOLTRES
	db MR_MIME, 	DEX_MR_MIME
	db MUK, 		DEX_MUK
	db NIDOKING, 	DEX_NIDOKING
	db NIDOQUEEN, 	DEX_NIDOQUEEN
	db NIDORAN_F, 	DEX_NIDORAN_F
	db NIDORAN_M, 	DEX_NIDORAN_M
	db NIDORINA, 	DEX_NIDORINA	; 90
	db NIDORINO, 	DEX_NIDORINO
	db NINETALES, 	DEX_NINETALES
	db ODDISH, 		DEX_ODDISH
	db OMANYTE, 	DEX_OMANYTE
	db OMASTAR, 	DEX_OMASTAR
	db ONIX, 		DEX_ONIX
	db PARAS, 		DEX_PARAS
	db PARASECT, 	DEX_PARASECT
	db PERSIAN, 	DEX_PERSIAN
	db PIDGEOT, 	DEX_PIDGEOT		;100
	db PIDGEOTTO,	DEX_PIDGEOTTO
	db PIDGEY, 		DEX_PIDGEY
	db PIKACHU, 	DEX_PIKACHU
	db PINSIR, 		DEX_PINSIR
	db POLIWAG, 	DEX_POLIWAG
	db POLIWHIRL, 	DEX_POLIWHIRL
	db POLIWRATH, 	DEX_POLIWRATH
	db PONYTA, 		DEX_PONYTA
	db PORYGON, 	DEX_PORYGON
	db PRIMEAPE, 	DEX_PRIMEAPE	;110
	db PSYDUCK, 	DEX_PSYDUCK
	db RAICHU, 		DEX_RAICHU
	db RAPIDASH, 	DEX_RAPIDASH
	db RATICATE, 	DEX_RATICATE
	db RATTATA, 	DEX_RATTATA
	db RHYDON, 		DEX_RHYDON
	db RHYHORN, 	DEX_RHYHORN
	db SANDSHREW, 	DEX_SANDSHREW
	db SANDSLASH, 	DEX_SANDSLASH
	db SCYTHER, 	DEX_SCYTHER		;120
	db SEADRA, 		DEX_SEADRA
	db SEAKING, 	DEX_SEAKING
	db SEEL, 		DEX_SEEL
	db SHELLDER, 	DEX_SHELLDER
	db SLOWBRO, 	DEX_SLOWBRO
	db SLOWPOKE, 	DEX_SLOWPOKE
	db SNORLAX, 	DEX_SNORLAX
	db SPEAROW, 	DEX_SPEAROW
	db SQUIRTLE, 	DEX_SQUIRTLE
	db STARMIE, 	DEX_STARMIE		;130
	db STARYU, 		DEX_STARYU
	db TANGELA, 	DEX_TANGELA
	db TAUROS, 		DEX_TAUROS
	db TENTACOOL, 	DEX_TENTACOOL
	db TENTACRUEL, 	DEX_TENTACRUEL
	db VAPOREON, 	DEX_VAPOREON
	db VENOMOTH,	DEX_VENOMOTH
	db VENONAT, 	DEX_VENONAT
	db VENUSAUR, 	DEX_VENUSAUR
	db VICTREEBEL, 	DEX_VICTREEBEL	;140
	db VILEPLUME, 	DEX_VILEPLUME
	db VOLTORB, 	DEX_VOLTORB
	db VULPIX, 		DEX_VULPIX
	db WARTORTLE, 	DEX_WARTORTLE
	db WEEDLE, 		DEX_WEEDLE
	db WEEPINBELL, 	DEX_WEEPINBELL
	db WEEZING, 	DEX_WEEZING
	db WIGGLYTUFF, 	DEX_WIGGLYTUFF
	db ZAPDOS, 		DEX_ZAPDOS
	db ZUBAT, 		DEX_ZUBAT		;150
	db -1